### ISSUE TITLE
Error obtaining the Android stats

### ISSUE THREAD

**Issue by sabadow** [ArcadiaConsulting/appstorestats#11]
The Google Play downloads aren't retrieved correctly, looks like there is an API change that breaks the library. The app throws this exception:

```
Caused by: org.json.JSONException: JSONObject["3"] not found.
	at org.json.JSONObject.get(JSONObject.java:498) [json-20090211.jar:]
	at org.json.JSONObject.getString(JSONObject.java:669) [json-20090211.jar:]
	at com.github.andlyticsproject.console.v2.JsonParser.parseApp(JsonParser.java:246) [appstoresstats-android-1.0.8.jar:]
	at com.github.andlyticsproject.console.v2.JsonParser.parseAppInfo(JsonParser.java:384) [appstoresstats-android-1.0.8.jar:]
	at com.github.andlyticsproject.console.v2.DevConsoleV2Protocol.parseAppInfoResponse(DevConsoleV2Protocol.java:168) [appstoresstats-android-1.0.8.jar:]
	... 50 more
```

The base project already has a patch for this issue: https://github.com/AndlyticsProject/andlytics/pull/683/files

**Comment by sabadow** [comment]
Fixed on version 1.0.9
